// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import logo from "../logo.svg";
import "./EditModal.css";
export default function EditModal({ row, onClose }) {
  if (!row) return null;
  return (
    <div className="modal-backdrop">
      <div className="modal-box">
        <div className="modal-header">
          <img src={logo} alt="Logo" className="header-logo" style={{ width: 40, height: 40, marginRight: 12 }} />
          <strong>Edit Power</strong>
          <button className="modal-x" onClick={onClose}>×</button>
        </div>
        <div className="modal-body">
          <label>Value: <input defaultValue={row.power}/></label>
          <div><span className="confbadge">{row.conf}</span></div>
          <div>Source: {row.ref}</div>
        </div>
        <div className="modal-footer">
          <button className="modal-flag">Flag for Review</button>
          <button className="modal-reject">Reject</button>
          <button className="modal-approve">Approve</button>
        </div>
      </div>
    </div>
  )
}