// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import logo from "../logo.svg";
import "./ExportFilePage.css";
export default function ExportFilePage() {
  return (
    <div className="export-root">
      <header className="export-header">
        <img src={logo} alt="Logo" className="header-logo" style={{ width: 40, height: 40, marginRight: 12 }} />
        <h2>AI Extraction Automation -  Export File Page</h2>
        <span style={{marginLeft:"auto"}}>Sneha</span>
      </header>
      <main className="export-panel">
        <h3>Extracted Data</h3>
        <div className="export-actions">
          <button>Approve Selected</button>
          <input placeholder="Search" />
          <button>Re-process</button>
          <div className="export-dropdown">
            <button>Export ▼</button>
            <div className="export-menu">
              <div>Export as XLSX</div>
              <div>Export as PDF</div>
              <div>Export as DOCX</div>
              <div>Export as TXT</div>
            </div>
          </div>
        </div>
        <div className="export-table-blur">
          <table>
            <thead>
              <tr>
                <th>Model</th>
                <th>Power</th>
                <th>Weight</th>
                <th>IP Rating</th>
                <th>Confidence</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Z900</td>
                <td>25W</td>
                <td>3kg</td>
                <td>IP54</td>
                <td><span className="confbadge">92%</span></td>
              </tr>
            </tbody>
          </table>
          <div className="blur-cover">Exported</div>
        </div>
      </main>
    </div>
  );
}