// // Code Generated by Sidekick is for learning and experimentation purposes only.
// import React from 'react';
// import logo from './logo.png';
// function TableView({ tableData }) {
//   return (
//     <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '12px' }}>
//       <thead>
//         <tr>
//           <th>Model</th>
//           <th>Power</th>
//           <th>Weight</th>
//           <th>IP Rating</th>
//           <th>Confidence</th>
//           <th>Source</th>
//         </tr>
//       </thead>
//       <tbody>
//         {/* Map your tableData here if available */}
//       </tbody>
//     </table>
//   );
// }
// export default TableView;



import React from "react";
import logo from "./logo.png";

function TableView({ tableData }) {
  return (
    <div style={{
      background: "rgba(255,255,255,0.6)",
      borderRadius: 16,
      padding: 20,
      boxShadow: "0 6px 20px rgba(0,0,0,0.1)",
      backdropFilter: "blur(10px)",
      marginTop: 20
    }}>
      <table style={{
        width: "100%",
        borderCollapse: "collapse",
        fontFamily: "'Inter', sans-serif"
      }}>
        <thead>
          <tr style={{
            background: "linear-gradient(135deg,#93c5fd,#c7d2fe)",
            color: "#1e293b"
          }}>
            <th style={cellStyle}>Model</th>
            <th style={cellStyle}>Power</th>
            <th style={cellStyle}>Weight</th>
            <th style={cellStyle}>IP Rating</th>
            <th style={cellStyle}>Confidence</th>
            <th style={cellStyle}>Source</th>
          </tr>
        </thead>
        <tbody>
          {/* Map tableData dynamically later */}
        </tbody>
      </table>
    </div>
  );
}

const cellStyle = {
  padding: "10px 12px",
  textAlign: "left",
  borderBottom: "2px solid rgba(255,255,255,0.3)",
  fontWeight: 600,
  fontSize: "0.95rem"
};

export default TableView;
