// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
function TopBar() {
  return (
    <header className="topbar">
      <span className="topbar-title">Your Project Title Here</span>
    </header>
  );
}
export default TopBar;