// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";

import LoginPage from "./components/LoginPage";
import UploadPage from "./components/UploadPage";
import DocReviewPage from "./components/DocReviewPage";
import ExtractionReviewPage from "./components/ExtractionReviewPage";
import EditModal from "./components/EditModal";
import ExportFilePage from "./components/ExportFilePage";
import VariantAttributePage from "./components/VariantAttributePage";


function App() {
  return (
    // <BrowserRouter>
      <Routes>
        <Route path="/" element={<LoginPage />} />
        <Route path="/upload" element={<UploadPage />} />
        <Route path="/review" element={<DocReviewPage />} />
        <Route path="/extraction_review" element={<ExtractionReviewPage />} />
        <Route path="/edit" element={<EditModal />} />
        <Route path="/export" element={<ExportFilePage />} />
        <Route path="/variant" element={<VariantAttributePage />} />

      </Routes>
    // </BrowserRouter>
  );
}

export default App;
