// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import logo from './logo.png';
function Modal({ cellData, onClose, onApprove, onReject, onFlag }) {
  if (!cellData) return null;
  return (
    <div style={{
      position: 'fixed', top: '25%', left: '25%', width: '300px', padding: '20px',
      backgroundColor: '#fff', border: '1px solid #333', zIndex: 100,
    }}>
      <h4>Edit & Approve/Reject</h4>
      <div>
        <input defaultValue={cellData.value} />
      </div>
      <button onClick={onApprove}>Approve</button>
      <button onClick={onReject}>Reject</button>
      <button onClick={onFlag}>Flag for Review</button>
      <button onClick={onClose}>Close</button>
    </div>
  );
}
export default Modal;